---
# from https://github.com/scoopex/puppet-kitchen_template
driver:
  provision: true

provisioner:
  name: puppet_apply
  modules_path: modules
  hiera_data_path: data
  hiera_data_remote_path: /tmp/kitchen/data
  hiera_deep_merge: true
  puppet_verbose: false
  puppet_debug: false
  require_chef_for_busser: false
  require_puppet_repo: false
  custom_options: '--show_diff'
  verify_host_key: false
  resolve_with_librarian_puppet: false
  resolve_with_r10k: true

transport:
  name: sftp

busser:
  ruby_bindir: /usr/bin

platforms:
  # vagrant automatically generates a hostname, if that exceeds 64 characters vbox fails, see bug #6
  - name: ubuntu18-kitchen_template
    driver_plugin: vagrant
    driver_config:
      customize:
        audio: "none"
    driver:
      vagrantfile_erb: vagrantfiles/Vagrantfile-debianoid.erb
      box: ubuntu/bionic64
      box_url: https://app.vagrantup.com/ubuntu/boxes/bionic64
  # TODO: setup docker driver, get docker image with working systemd, and test on travis.
suites:
  - name: bitbar
    provisioner:
      manifests_path: manifests-kitchen/bitbar
    verifier:
      inspec_tests:
        - test/integration/bitbar
    includes:
      - ubuntu18-kitchen_template
    attributes:
