---
# from https://github.com/scoopex/puppet-kitchen_template
driver:
  provision: true

provisioner:
  name: puppet_apply
  modules_path: modules
  hiera_data_path: data
  hiera_data_remote_path: /tmp/kitchen/data
  hiera_deep_merge: true
  hiera_writer_files:
    - secrets/vault.yaml:
        cltbld_user:
          password: 'abc123'
          salt: 'h3hhahchahah'
          iterations: '3'
          vnc_password: 'vnc4free'
        generic_worker:
          gecko_t_linux_talos:
            taskcluster_client_id: '123'
            taskcluster_access_token: 'foo'
            livelog_secret: 'haha'
            quarantine_client_id: '3333'
            quarantine_access_token: 'Q_TOKEN'
            bugzilla_api_key: 'BZ_KEY'
  puppet_verbose: true
  puppet_debug: true
  require_chef_for_busser: false
  require_puppet_omnibus: true
  require_puppet_repo: false
  custom_options: '--show_diff'
  verify_host_key: false
  resolve_with_librarian_puppet: false
  resolve_with_r10k: true

verifier:
  name: serverspec
  default_pattern: true

busser:
  ruby_bindir: /usr/bin

platforms:
  # vagrant automatically generates a hostname, if that exceeds 64 characters vbox fails, see bug #6
  - name: ubuntu18-kitchen_template
    driver_plugin: vagrant
    driver_config:
      customize:
        audio: "none"
    driver:
      vagrantfile_erb: vagrantfiles/Vagrantfile-debianoid.erb
      box: ubuntu/bionic64
      box_url: https://app.vagrantup.com/ubuntu/boxes/bionic64
  # TODO: setup docker driver, get docker image with working systemd, and test on travis.
suites:
  - name: linux
    provisioner:
      manifests_path: manifests-kitchen/linux
    includes:
      - ubuntu18-kitchen_template
    attributes:
  - name: bitbar
    provisioner:
      manifests_path: manifests-kitchen/bitbar
    includes:
      - ubuntu18-kitchen_template
    attributes:
  - name: maas_region
    provisioner:
      manifests_path: manifests-kitchen/maas_region
    includes:
      - ubuntu18-kitchen_template
    attributes:
  - name: maas_rack
    provisioner:
      manifests_path: manifests-kitchen/maas_rack
    includes:
      - ubuntu18-kitchen_template
    attributes:
