---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /bin/systemd
  cap_add:
    - SYS_ADMIN

provisioner:
  name: puppet_apply
  modules_path: modules
  hiera_data_path: data
  hiera_data_remote_path: /tmp/kitchen/data
  hiera_deep_merge: true
  hiera_writer_files:
    - secrets/vault.yaml:
        cltbld_user:
          password: 'abc123'
          salt: 'h3hhahchahah'
          iterations: '3'
          vnc_password: 'vnc4free'
        generic_worker:
          gecko_t_linux_talos:
            taskcluster_client_id: '123'
            taskcluster_access_token: 'foo'
            livelog_secret: 'haha'
            quarantine_client_id: '3333'
            quarantine_access_token: 'Q_TOKEN'
            bugzilla_api_key: 'BZ_KEY'
  provision_command: locale-gen en_US.UTF-8; apt-get install dbus
  puppet_verbose: true
  puppet_debug: true
  require_chef_for_busser: true
  require_puppet_repo: false
  custom_options: '--show_diff'
  verify_host_key: false
  resolve_with_librarian_puppet: false
  resolve_with_r10k: true

platforms:
  - name: ubuntu-18.04

busser:
  sudo: true

suites:
  - name: linux
    provisioner:
      manifests_path: manifests-kitchen/linux
    verifier:
      inspec_tests:
        - test/integration/linux
    attributes:
  - name: bitbar
    provisioner:
      manifests_path: manifests-kitchen/bitbar
    verifier:
      inspec_tests:
        - test/integration/bitbar
    attributes:
  - name: maas
    provisioner:
      manifests_path: manifests-kitchen/maas-region
    # verifier:
    #   inspec_tests:
    #     - test/integration/maas-region
    attributes:
  - name: maas_rack
    provisioner:
      manifests_path: manifests-kitchen/maas-rack
    # verifier:
    #   inspec_tests:
    #     - test/integration/maas-rack
    attributes:
