# require_relative 'spec_helper'

# describe command('crontab -l -u root') do
#   its(:stdout) do
#     should match(%r{^# HEADER: This file was autogenerated at .+ by puppet.\n# HEADER: While it can still be managed manually, it is definitely not recommended.\n# HEADER: Note particularly that the comments starting with 'Puppet Name' should\n# HEADER: not be deleted, as doing so could cause duplicate cron jobs.\n# Puppet Name: gw_checker\n\*/30 \* \* \* \* /usr/local/bin/gw_checker.sh$})
#   end
# end
