#!/usr/bin/env python3

import json

template = r'''#!/usr/bin/env bash
# shellcheck disable=all

# set -e
#set -x

# this is a repackaging of the chrome deb package's postinst script
# from https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#
# generated by process.py

BULK_GOES_HERE

CURSIVE=$(cat <<'EOF'
                                                                  _  _
     /                                                  _/_      // //
 _. /_  __  __ ______  _    __  _  _   __   o ____  _   /  __.  // // _  __
(__/ /_/ (_(_)/ / / <_</_  / (_</_/_)_(_)  <_/ / <_/_)_<__(_/|_</_</_</_/ (_
                                 /
                                '
EOF
)

LOCKERGNOME=$(cat <<'EOF'
     :|                                               ++            :|       :| :|
.::/ :::| :::| ,::\ :\/| :~~/   :::| :~~/ :::\ ,::\   :| :::\ <::< :::| .::\ :| :| :~~/ :::|
`::\ :|:| :|   `::/ :::| :::,   :|   :::, :::/ `::/   :| :|:| >::>  :|  `::| :| :| :::, :|
                                          :|
EOF
)

# main
echo "$LOCKERGNOME"
install_key
handle_distro_upgrade
update_bad_sources
create_sources_lists
echo "done"
'''



def extract_nodes(node, src, results):
    # Function definitions
    if node.get("Type") == "FuncDecl":
        start, end = node["Pos"]["Offset"], node["End"]["Offset"]
        results.append(src[start:end].decode())
    # Assignments at the top level or inside commands
    elif node.get("Type") == "CallExpr" and "Assigns" in node:
        for assign in node["Assigns"]:
            start, end = assign["Pos"]["Offset"], assign["End"]["Offset"]
            results.append(src[start:end].decode())
    # Recurse into possible child lists
    for key in ("Stmts", "Then", "Else", "Do", "Body"):
        child = node.get(key)
        if isinstance(child, dict):
            extract_nodes(child, src, results)
        elif isinstance(child, list):
            for item in child:
                if isinstance(item, dict):
                    extract_nodes(item, src, results)
    # For function bodies, look inside the "Body"->"Cmd"
    if node.get("Type") == "FuncDecl" and "Body" in node and "Cmd" in node["Body"]:
        extract_nodes(node["Body"]["Cmd"], src, results)
    # For if/for/case/etc, look inside "Cmd"
    if "Cmd" in node and isinstance(node["Cmd"], dict):
        extract_nodes(node["Cmd"], src, results)


# main
if __name__ == '__main__':
    with open('postinst', 'rb') as f:
        src = f.read()

    with open('ast.json') as f:
        ast = json.load(f)

    results = []
    # Start from the 'List' field of the root node
    for node in ast.get('Stmts', []):
        extract_nodes(node, src, results)

    # phase 1: just show the output
    # with open('postinst_filtered', 'w') as f:
    #     for line in results:
    #         f.write(line)
    #         f.write('\n')

    # phase 2: output the `install_repo_automated` script
    with open('install_repo_automated', 'w') as f:
        f.write(template.replace("BULK_GOES_HERE", "\n".join(results)))
