name: r10k

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  r10k-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          bundler-cache: false

      - name: Cache gems
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.gem
          key: v1-gems-${{ runner.os }}-${{ hashFiles('.ruby-version', 'Gemfile.lock') }}

      - name: Bundle install
        run: |
          gem install bundler:2.5.23
          bundle install

      - name: r10k puppetfile install
        run: bundle exec r10k puppetfile install --moduledir=/tmp/r10k_module_test -v --force
