name: r10k

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  r10k-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.221.0
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Cache gems
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.gem
          key: v1-gems-${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}

      - name: Bundle install
        run: |
          gem install bundler:2.5.23
          bundle install

      - name: r10k puppetfile install
        run: bundle exec r10k puppetfile install --moduledir=/tmp/r10k_module_test -v --force
